CREATE TABLE IF NOT EXISTS summaries (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  eventReference VARCHAR(30) NOT NULL,
  eventDate DATE NULL,
  eventTitle VARCHAR(80) NOT NULL,
  eventText MEDIUMTEXT NOT NULL 
);